# Generated by Django 4.2 on 2023-04-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
