# Generated by Django 4.2 on 2023-04-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0002_alter_book_author_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_year',
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
